create table
  public.users (
    user_id bigint generated by default as identity,
    user_name text null default ''::text,
    password text null default ''::text,
    constraint users_pkey primary key (user_id)
  ) tablespace pg_default;

create table
  public.tasks (
    task_id integer generated by default as identity,
    name text null default ''::text,
    description text null default ''::text,
    priority text null default ''::text,
    status text null default ''::text,
    start_date timestamp with time zone null,
    due_date timestamp with time zone null,
    end_date timestamp with time zone null,
    user_id bigint null,
    constraint tasks_pkey primary key (task_id),
    constraint tasks_user_id_fkey foreign key (user_id) references users (user_id)
  ) tablespace pg_default;

create table
  public.tags (
    tag_id bigint generated by default as identity,
    name text null default ''::text,
    user_id bigint null,
    task_id integer null,
    constraint tags_pkey primary key (tag_id),
    constraint tags_task_id_fkey foreign key (task_id) references tasks (task_id),
    constraint tags_user_id_fkey foreign key (user_id) references users (user_id)
  ) tablespace pg_default;